### ISSUE TITLE
님 오타남

### ISSUE THREAD

**Issue by OruteZ** [Famec7/GitRepository1#1]
[GitFile1](https://github.com/Famec7/GitRepository1/blob/master/GitFile1.txt) 에서 오타남
`contenst3` ==> `contents3` 로 바꿔주세요 ^^7

**Comment by Famec7** [comment]
> [GitFile1](https://github.com/Famec7/GitRepository1/blob/master/GitFile1.txt) 에서 오타남 `contenst3` ==> `contents3` 로 바꿔주세요 ^^7

찾아주셔서 감사합니다^^7
